# Generated by Django 5.2.1 on 2025-06-04 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_team_name', models.CharField(max_length=100)),
                ('jersey_color', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('circuit_or_level', models.CharField(max_length=100)),
                ('game_date', models.DateField()),
                ('performance_note', models.TextField(blank=True)),
                ('coach_name', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
