# Generated by Django 5.2.1 on 2025-06-04 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_gamevideocoach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamScoutingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(help_text='Title of the player report', max_length=255)),
                ('overview', models.TextField()),
                ('strengths', models.JSONField(default=list, help_text='List of strengths')),
                ('weaknesses', models.JSONField(default=list, help_text='List of weaknesses')),
                ('key_players', models.TextField()),
                ('tendencies', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='Report creation date and time')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Report last updated date and time')),
                ('coach_name', models.ForeignKey(help_text='Select the coach for whom the report is being created', limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
