# Generated by Django 5.2.1 on 2025-06-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_teamscoutingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_team_name', models.CharField(max_length=100)),
                ('jersey_color', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('circuit_or_level', models.CharField(max_length=100)),
                ('game_date', models.DateField()),
                ('performance_note', models.TextField(blank=True)),
                ('youtube_link', models.URLField(blank=True, help_text='Paste YouTube video link', null=True)),
                ('uploaded_video', models.FileField(blank=True, null=True, upload_to='game_videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='coach',
            name='coach_name',
        ),
        migrations.DeleteModel(
            name='GameVideoCoach',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
