# Generated by Django 5.2.1 on 2025-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_teaminformation_remove_coach_coach_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamscoutingreport',
            options={'verbose_name': 'Team Scouting Report', 'verbose_name_plural': 'Team Scouting Reports'},
        ),
        migrations.RemoveField(
            model_name='teamscoutingreport',
            name='coach_name',
        ),
        migrations.AlterField(
            model_name='teamscoutingreport',
            name='report_title',
            field=models.CharField(help_text='Title of the scouting report', max_length=200),
        ),
    ]
