# Generated by Django 5.2.1 on 2025-06-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_alter_teamscoutingreport_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamScoutingReport',
            new_name='TeamScouting',
        ),
    ]
