# Generated by Django 5.2.1 on 2025-06-03 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveIntegerField()),
                ('height', models.FloatField(help_text='Height in cm or inches')),
                ('position', models.CharField(max_length=50)),
                ('class_year', models.CharField(max_length=10)),
                ('game_context', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('opponent_team_name', models.CharField(max_length=100)),
                ('performance_note', models.TextField(blank=True)),
                ('player_name', models.ForeignKey(limit_choices_to={'is_player': True}, on_delete=django.db.models.deletion.CASCADE, related_name='player_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
