# Generated by Django 5.2.1 on 2025-06-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the video', max_length=255, null=True)),
                ('youtube_link', models.URLField(blank=True, help_text='Paste YouTube video link', null=True)),
                ('uploaded_video', models.FileField(blank=True, null=True, upload_to='game_videos/')),
            ],
            options={
                'verbose_name': 'Game Video',
                'verbose_name_plural': 'Game Videos',
            },
        ),
        migrations.CreateModel(
            name='ScoutingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=255)),
                ('game_result', models.CharField(max_length=50)),
                ('opponent_faced', models.CharField(max_length=255)),
                ('score_or_margin', models.CharField(max_length=50)),
                ('game_flow_details', models.TextField()),
            ],
        ),
    ]
