# Generated by Django 5.2.1 on 2025-06-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_gamevideo_scoutingcontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
