# Generated by Django 5.2.1 on 2025-06-04 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_player_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
                ('strengths', models.JSONField(default=list, help_text='List of strengths')),
                ('weaknesses', models.JSONField(default=list, help_text='List of weaknesses')),
                ('projection', models.TextField()),
                ('field_goal_percentage', models.FloatField(help_text='Field Goal Percentage')),
                ('rebounds', models.IntegerField(help_text='Total Rebounds')),
                ('assists', models.IntegerField(help_text='Total Assists')),
                ('steals_and_blocks', models.IntegerField(help_text='Total Steals & Blocks')),
                ('player_name', models.ForeignKey(help_text='Select the player for whom the report is being created', limit_choices_to={'is_player': True}, on_delete=django.db.models.deletion.CASCADE, related_name='player_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
