# Generated by Django 5.2.1 on 2025-06-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_playerreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerReport',
        ),
    ]
