# Generated by Django 5.2.1 on 2025-06-05 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_playerreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameVideo',
        ),
        migrations.DeleteModel(
            name='ScoutingContext',
        ),
    ]
