# Generated by Django 5.2.1 on 2025-06-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_delete_gamevideo_delete_scoutingcontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=255)),
                ('game_result', models.CharField(max_length=50)),
                ('opponent_faced', models.CharField(max_length=255)),
                ('score_or_margin', models.CharField(max_length=50)),
                ('game_flow_details', models.TextField()),
                ('game_video', models.FileField(blank=True, help_text='Upload game video if available', null=True, upload_to='game_videos/')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='Scouting Context creation date and time')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Scouting Context last updated date and time')),
            ],
        ),
    ]
