# Generated by Django 5.2.1 on 2025-06-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_scoutingcontext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_name',
        ),
        migrations.DeleteModel(
            name='ScoutingContext',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
