# Generated by Django 5.2.1 on 2025-06-05 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_remove_player_player_name_delete_scoutingcontext_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=255)),
                ('game_result', models.CharField(max_length=50)),
                ('opponent_faced', models.CharField(max_length=255)),
                ('score_or_margin', models.CharField(max_length=50)),
                ('game_flow_details', models.TextField()),
                ('game_video', models.FileField(blank=True, help_text='Upload game video if available', null=True, upload_to='game_videos/')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='Scouting Context creation date and time')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Scouting Context last updated date and time')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveIntegerField()),
                ('height', models.FloatField(help_text='Height in cm or inches')),
                ('position', models.CharField(max_length=50)),
                ('class_year', models.CharField(max_length=10)),
                ('game_context', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('opponent_team_name', models.CharField(max_length=100)),
                ('performance_note', models.TextField(blank=True)),
                ('player_name', models.ForeignKey(limit_choices_to={'is_player': True}, on_delete=django.db.models.deletion.CASCADE, related_name='player_profiles', to=settings.AUTH_USER_MODEL)),
                ('scouting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='player.scoutingcontext')),
            ],
        ),
    ]
