# Generated by Django 5.2.1 on 2025-06-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_scoutingcontext_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='ScoutingContext',
        ),
    ]
