# Generated by Django 5.2.1 on 2025-06-10 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_player_scoutingcontext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoutingcontext',
            name='player',
        ),
        migrations.AddField(
            model_name='scoutingcontext',
            name='player_name',
            field=models.ForeignKey(limit_choices_to={'is_player': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_scouting', to=settings.AUTH_USER_MODEL),
        ),
    ]
