# Generated by Django 5.2.1 on 2025-06-10 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_remove_scoutingcontext_player_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoutingContext',
        ),
    ]
