# Generated by Django 5.2.1 on 2025-06-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_scoutingcontext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoutingContext',
        ),
    ]
