# Generated by Django 5.2.1 on 2025-06-10 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_scoutingcontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerreport',
            name='assists',
            field=models.IntegerField(help_text='Assists', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='field_goal_percentage',
            field=models.FloatField(help_text='Field Goal Percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='rebounds',
            field=models.IntegerField(help_text='Rebounds', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='steals_and_blocks',
            field=models.IntegerField(help_text='Steals & Blocks', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
