# Generated by Django 5.2.1 on 2025-06-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0018_alter_playerreport_assists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload player image', null=True, upload_to='player_images/'),
        ),
    ]
