# Generated by Django 5.2.1 on 2025-06-24 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0019_player_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoutingcontext',
            name='player_name',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='ScoutingContext',
        ),
    ]
